# Generated by Django 2.1.5 on 2019-01-20 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('author', models.CharField(max_length=150)),
                ('item_date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_date_updated', models.DateTimeField(auto_now=True)),
                ('book_date_published', models.DateField()),
            ],
        ),
    ]
