# Generated by Django 2.1.5 on 2019-01-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock_available',
            field=models.BigIntegerField(default=5),
        ),
    ]
