# Generated by Django 2.1.5 on 2019-01-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190120_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(default='no_img.png', null=True, upload_to='pics'),
        ),
    ]
