# Generated by Django 2.1.5 on 2019-01-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190121_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(default='pics/no_img.png', null=True, upload_to='pics'),
        ),
    ]
