# Generated by Django 2.1.5 on 2019-01-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190121_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen', models.CharField(help_text='Enter A Book Genre (e.g. Sci-Fi, Programming etc.', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(help_text='Book Author', max_length=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(help_text='Book Short Desciption', max_length=1500),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(help_text='Book Link'),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock_available',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Book Title', max_length=150),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(default='Sci-Fi', help_text='Select Genres For This Book', null=True, to='shop.Genres'),
        ),
    ]
