# Generated by Django 2.1.5 on 2019-01-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190122_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select Genres For This Book', null=True, to='shop.Genres'),
        ),
    ]
