# Generated by Django 2.1.5 on 2019-01-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190122_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(default='sda', help_text='Select Genres For This Book', to='shop.Genres'),
        ),
    ]
