# Generated by Django 2.1.5 on 2019-01-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20190122_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='gen',
            new_name='name',
        ),
    ]
