# Generated by Django 2.1.5 on 2019-01-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20190122_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select Genres For This Book', to='shop.Genre'),
        ),
    ]
