# Generated by Django 2.1.5 on 2019-01-23 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20190123_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Author Name', max_length=100)),
                ('f_name', models.CharField(help_text='Author Family Name', max_length=100)),
                ('date_of_birth', models.DateField(null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text='Select Author For This Book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(help_text='Book Short Description', max_length=1500),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Book Genre (e.g. Sci-Fi, Programming etc.', max_length=100),
        ),
    ]
