# Generated by Django 2.1.5 on 2019-01-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20190123_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='auth',
        ),
    ]
