# Generated by Django 2.1.5 on 2019-01-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20190123_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='f_name',
            field=models.CharField(help_text='Author Family Name', max_length=100, verbose_name='family name'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Book Genre (e.g. Sci-Fi, Programming etc.', max_length=100, verbose_name='Genre'),
        ),
    ]
