# Generated by Django 2.1.5 on 2019-01-23 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20190123_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Author Name', max_length=100)),
                ('f_name', models.CharField(help_text='Author Family Name', max_length=100, verbose_name='family name')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text='Select Author For This Book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Author'),
        ),
    ]
