# Generated by Django 2.1.5 on 2019-01-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20190123_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, help_text='Author Link', null=True),
        ),
    ]
