# Generated by Django 2.1.5 on 2019-01-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(help_text='Author Link'),
        ),
    ]
